name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download code from repository
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # Step 2: Provision a clean Java Environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Step 3: Run Maven compile and tests
    - name: Build and Test Application
      run: mvn clean package

    # Step 4: Archive compiled file
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-jar
        path: target/*.jar